//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleAccessDemo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Page
    {
        public Page()
        {
            this.PageAccesses = new HashSet<PageAccess>();
        }
    
        public int ID { get; set; }
        public string PageName { get; set; }
        public string ParentPageID { get; set; }
    
        public virtual ICollection<PageAccess> PageAccesses { get; set; }
    }
}
