//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleAccessDemo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageAccess
    {
        public int ID { get; set; }
        public Nullable<int> PageID { get; set; }
        public Nullable<int> UserRoleID { get; set; }
        public Nullable<bool> View { get; set; }
        public Nullable<bool> Edit { get; set; }
        public Nullable<bool> Add { get; set; }
        public Nullable<bool> Delete { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
