//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RoleAccessDemo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRole
    {
        public UserRole()
        {
            this.PageAccesses = new HashSet<PageAccess>();
            this.Users = new HashSet<User>();
        }
    
        public int ID { get; set; }
        public string UserRole1 { get; set; }
    
        public virtual ICollection<PageAccess> PageAccesses { get; set; }
        public virtual ICollection<User> Users { get; set; }
        public virtual UserRole UserRole11 { get; set; }
        public virtual UserRole UserRole2 { get; set; }
        public virtual UserRole UserRole12 { get; set; }
        public virtual UserRole UserRole3 { get; set; }
    }
}
